name: Auto Comment on New Issues

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the new issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.actor }}, thanks for submitting this issue! A representative from the Open UI team will respond to you shortly.

            
